// <auto-generated />
using System;
using LandmarkApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LandmarkApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260109202100_SeedStates")]
    partial class SeedStates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LandmarkApi.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IbgeCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IbgeCode")
                        .IsUnique();

                    b.HasIndex("StateId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("LandmarkApi.Domain.Entities.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("IbgeCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Acronym")
                        .IsUnique();

                    b.HasIndex("IbgeCode")
                        .IsUnique();

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Acronym = "AC",
                            IbgeCode = "12",
                            Name = "Acre"
                        },
                        new
                        {
                            Id = 2,
                            Acronym = "AL",
                            IbgeCode = "27",
                            Name = "Alagoas"
                        },
                        new
                        {
                            Id = 3,
                            Acronym = "AP",
                            IbgeCode = "16",
                            Name = "Amapá"
                        },
                        new
                        {
                            Id = 4,
                            Acronym = "AM",
                            IbgeCode = "13",
                            Name = "Amazonas"
                        },
                        new
                        {
                            Id = 5,
                            Acronym = "BA",
                            IbgeCode = "29",
                            Name = "Bahia"
                        },
                        new
                        {
                            Id = 6,
                            Acronym = "CE",
                            IbgeCode = "23",
                            Name = "Ceará"
                        },
                        new
                        {
                            Id = 7,
                            Acronym = "DF",
                            IbgeCode = "53",
                            Name = "Distrito Federal"
                        },
                        new
                        {
                            Id = 8,
                            Acronym = "ES",
                            IbgeCode = "32",
                            Name = "Espírito Santo"
                        },
                        new
                        {
                            Id = 9,
                            Acronym = "GO",
                            IbgeCode = "52",
                            Name = "Goiás"
                        },
                        new
                        {
                            Id = 10,
                            Acronym = "MA",
                            IbgeCode = "21",
                            Name = "Maranhão"
                        },
                        new
                        {
                            Id = 11,
                            Acronym = "MT",
                            IbgeCode = "51",
                            Name = "Mato Grosso"
                        },
                        new
                        {
                            Id = 12,
                            Acronym = "MS",
                            IbgeCode = "50",
                            Name = "Mato Grosso do Sul"
                        },
                        new
                        {
                            Id = 13,
                            Acronym = "MG",
                            IbgeCode = "31",
                            Name = "Minas Gerais"
                        },
                        new
                        {
                            Id = 14,
                            Acronym = "PA",
                            IbgeCode = "15",
                            Name = "Pará"
                        },
                        new
                        {
                            Id = 15,
                            Acronym = "PB",
                            IbgeCode = "25",
                            Name = "Paraíba"
                        },
                        new
                        {
                            Id = 16,
                            Acronym = "PR",
                            IbgeCode = "41",
                            Name = "Paraná"
                        },
                        new
                        {
                            Id = 17,
                            Acronym = "PE",
                            IbgeCode = "26",
                            Name = "Pernambuco"
                        },
                        new
                        {
                            Id = 18,
                            Acronym = "PI",
                            IbgeCode = "22",
                            Name = "Piauí"
                        },
                        new
                        {
                            Id = 19,
                            Acronym = "RJ",
                            IbgeCode = "33",
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 20,
                            Acronym = "RN",
                            IbgeCode = "24",
                            Name = "Rio Grande do Norte"
                        },
                        new
                        {
                            Id = 21,
                            Acronym = "RS",
                            IbgeCode = "43",
                            Name = "Rio Grande do Sul"
                        },
                        new
                        {
                            Id = 22,
                            Acronym = "RO",
                            IbgeCode = "11",
                            Name = "Rondônia"
                        },
                        new
                        {
                            Id = 23,
                            Acronym = "RR",
                            IbgeCode = "14",
                            Name = "Roraima"
                        },
                        new
                        {
                            Id = 24,
                            Acronym = "SC",
                            IbgeCode = "42",
                            Name = "Santa Catarina"
                        },
                        new
                        {
                            Id = 25,
                            Acronym = "SP",
                            IbgeCode = "35",
                            Name = "São Paulo"
                        },
                        new
                        {
                            Id = 26,
                            Acronym = "SE",
                            IbgeCode = "28",
                            Name = "Sergipe"
                        },
                        new
                        {
                            Id = 27,
                            Acronym = "TO",
                            IbgeCode = "17",
                            Name = "Tocantins"
                        });
                });

            modelBuilder.Entity("LandmarkApi.Domain.Entities.TouristPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("TouristPoints", (string)null);
                });

            modelBuilder.Entity("LandmarkApi.Domain.Entities.City", b =>
                {
                    b.HasOne("LandmarkApi.Domain.Entities.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("LandmarkApi.Domain.Entities.TouristPoint", b =>
                {
                    b.HasOne("LandmarkApi.Domain.Entities.City", "City")
                        .WithMany("TouristPoints")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("LandmarkApi.Domain.Entities.City", b =>
                {
                    b.Navigation("TouristPoints");
                });

            modelBuilder.Entity("LandmarkApi.Domain.Entities.State", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
