// <auto-generated />
using System;
using LandmarkApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LandmarkApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260109202917_SeedCities")]
    partial class SeedCities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LandmarkApi.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IbgeCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IbgeCode")
                        .IsUnique();

                    b.HasIndex("StateId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IbgeCode = "1100205",
                            Name = "Porto Velho",
                            StateId = 22
                        },
                        new
                        {
                            Id = 2,
                            IbgeCode = "1100122",
                            Name = "Ji-Paraná",
                            StateId = 22
                        },
                        new
                        {
                            Id = 3,
                            IbgeCode = "1100023",
                            Name = "Ariquemes",
                            StateId = 22
                        },
                        new
                        {
                            Id = 4,
                            IbgeCode = "1200401",
                            Name = "Rio Branco",
                            StateId = 1
                        },
                        new
                        {
                            Id = 5,
                            IbgeCode = "1200203",
                            Name = "Cruzeiro do Sul",
                            StateId = 1
                        },
                        new
                        {
                            Id = 6,
                            IbgeCode = "1302603",
                            Name = "Manaus",
                            StateId = 4
                        },
                        new
                        {
                            Id = 7,
                            IbgeCode = "1303403",
                            Name = "Parintins",
                            StateId = 4
                        },
                        new
                        {
                            Id = 8,
                            IbgeCode = "1301902",
                            Name = "Itacoatiara",
                            StateId = 4
                        },
                        new
                        {
                            Id = 9,
                            IbgeCode = "1400100",
                            Name = "Boa Vista",
                            StateId = 23
                        },
                        new
                        {
                            Id = 10,
                            IbgeCode = "1400472",
                            Name = "Rorainópolis",
                            StateId = 23
                        },
                        new
                        {
                            Id = 11,
                            IbgeCode = "1501402",
                            Name = "Belém",
                            StateId = 14
                        },
                        new
                        {
                            Id = 12,
                            IbgeCode = "1500800",
                            Name = "Ananindeua",
                            StateId = 14
                        },
                        new
                        {
                            Id = 13,
                            IbgeCode = "1506807",
                            Name = "Santarém",
                            StateId = 14
                        },
                        new
                        {
                            Id = 14,
                            IbgeCode = "1504208",
                            Name = "Marabá",
                            StateId = 14
                        },
                        new
                        {
                            Id = 15,
                            IbgeCode = "1600303",
                            Name = "Macapá",
                            StateId = 3
                        },
                        new
                        {
                            Id = 16,
                            IbgeCode = "1600600",
                            Name = "Santana",
                            StateId = 3
                        },
                        new
                        {
                            Id = 17,
                            IbgeCode = "1721000",
                            Name = "Palmas",
                            StateId = 27
                        },
                        new
                        {
                            Id = 18,
                            IbgeCode = "1702109",
                            Name = "Araguaína",
                            StateId = 27
                        },
                        new
                        {
                            Id = 19,
                            IbgeCode = "1709500",
                            Name = "Gurupi",
                            StateId = 27
                        },
                        new
                        {
                            Id = 20,
                            IbgeCode = "2111300",
                            Name = "São Luís",
                            StateId = 10
                        },
                        new
                        {
                            Id = 21,
                            IbgeCode = "2105302",
                            Name = "Imperatriz",
                            StateId = 10
                        },
                        new
                        {
                            Id = 22,
                            IbgeCode = "2103000",
                            Name = "Caxias",
                            StateId = 10
                        },
                        new
                        {
                            Id = 23,
                            IbgeCode = "2211001",
                            Name = "Teresina",
                            StateId = 18
                        },
                        new
                        {
                            Id = 24,
                            IbgeCode = "2207702",
                            Name = "Parnaíba",
                            StateId = 18
                        },
                        new
                        {
                            Id = 25,
                            IbgeCode = "2208007",
                            Name = "Picos",
                            StateId = 18
                        },
                        new
                        {
                            Id = 26,
                            IbgeCode = "2304400",
                            Name = "Fortaleza",
                            StateId = 6
                        },
                        new
                        {
                            Id = 27,
                            IbgeCode = "2303709",
                            Name = "Caucaia",
                            StateId = 6
                        },
                        new
                        {
                            Id = 28,
                            IbgeCode = "2307304",
                            Name = "Juazeiro do Norte",
                            StateId = 6
                        },
                        new
                        {
                            Id = 29,
                            IbgeCode = "2312908",
                            Name = "Sobral",
                            StateId = 6
                        },
                        new
                        {
                            Id = 30,
                            IbgeCode = "2408102",
                            Name = "Natal",
                            StateId = 20
                        },
                        new
                        {
                            Id = 31,
                            IbgeCode = "2408003",
                            Name = "Mossoró",
                            StateId = 20
                        },
                        new
                        {
                            Id = 32,
                            IbgeCode = "2403251",
                            Name = "Parnamirim",
                            StateId = 20
                        },
                        new
                        {
                            Id = 33,
                            IbgeCode = "2507507",
                            Name = "João Pessoa",
                            StateId = 15
                        },
                        new
                        {
                            Id = 34,
                            IbgeCode = "2504009",
                            Name = "Campina Grande",
                            StateId = 15
                        },
                        new
                        {
                            Id = 35,
                            IbgeCode = "2513703",
                            Name = "Santa Rita",
                            StateId = 15
                        },
                        new
                        {
                            Id = 36,
                            IbgeCode = "2611606",
                            Name = "Recife",
                            StateId = 17
                        },
                        new
                        {
                            Id = 37,
                            IbgeCode = "2607901",
                            Name = "Jaboatão dos Guararapes",
                            StateId = 17
                        },
                        new
                        {
                            Id = 38,
                            IbgeCode = "2609600",
                            Name = "Olinda",
                            StateId = 17
                        },
                        new
                        {
                            Id = 39,
                            IbgeCode = "2604106",
                            Name = "Caruaru",
                            StateId = 17
                        },
                        new
                        {
                            Id = 40,
                            IbgeCode = "2704302",
                            Name = "Maceió",
                            StateId = 2
                        },
                        new
                        {
                            Id = 41,
                            IbgeCode = "2700300",
                            Name = "Arapiraca",
                            StateId = 2
                        },
                        new
                        {
                            Id = 42,
                            IbgeCode = "2800308",
                            Name = "Aracaju",
                            StateId = 26
                        },
                        new
                        {
                            Id = 43,
                            IbgeCode = "2804607",
                            Name = "Nossa Senhora do Socorro",
                            StateId = 26
                        },
                        new
                        {
                            Id = 44,
                            IbgeCode = "2927408",
                            Name = "Salvador",
                            StateId = 5
                        },
                        new
                        {
                            Id = 45,
                            IbgeCode = "2910800",
                            Name = "Feira de Santana",
                            StateId = 5
                        },
                        new
                        {
                            Id = 46,
                            IbgeCode = "2933307",
                            Name = "Vitória da Conquista",
                            StateId = 5
                        },
                        new
                        {
                            Id = 47,
                            IbgeCode = "2905701",
                            Name = "Camaçari",
                            StateId = 5
                        },
                        new
                        {
                            Id = 48,
                            IbgeCode = "3106200",
                            Name = "Belo Horizonte",
                            StateId = 13
                        },
                        new
                        {
                            Id = 49,
                            IbgeCode = "3170206",
                            Name = "Uberlândia",
                            StateId = 13
                        },
                        new
                        {
                            Id = 50,
                            IbgeCode = "3118601",
                            Name = "Contagem",
                            StateId = 13
                        },
                        new
                        {
                            Id = 51,
                            IbgeCode = "3136702",
                            Name = "Juiz de Fora",
                            StateId = 13
                        },
                        new
                        {
                            Id = 52,
                            IbgeCode = "3205309",
                            Name = "Vitória",
                            StateId = 8
                        },
                        new
                        {
                            Id = 53,
                            IbgeCode = "3205200",
                            Name = "Vila Velha",
                            StateId = 8
                        },
                        new
                        {
                            Id = 54,
                            IbgeCode = "3205002",
                            Name = "Serra",
                            StateId = 8
                        },
                        new
                        {
                            Id = 55,
                            IbgeCode = "3304557",
                            Name = "Rio de Janeiro",
                            StateId = 19
                        },
                        new
                        {
                            Id = 56,
                            IbgeCode = "3304904",
                            Name = "São Gonçalo",
                            StateId = 19
                        },
                        new
                        {
                            Id = 57,
                            IbgeCode = "3301702",
                            Name = "Duque de Caxias",
                            StateId = 19
                        },
                        new
                        {
                            Id = 58,
                            IbgeCode = "3303302",
                            Name = "Niterói",
                            StateId = 19
                        },
                        new
                        {
                            Id = 59,
                            IbgeCode = "3550308",
                            Name = "São Paulo",
                            StateId = 25
                        },
                        new
                        {
                            Id = 60,
                            IbgeCode = "3518800",
                            Name = "Guarulhos",
                            StateId = 25
                        },
                        new
                        {
                            Id = 61,
                            IbgeCode = "3509502",
                            Name = "Campinas",
                            StateId = 25
                        },
                        new
                        {
                            Id = 62,
                            IbgeCode = "3548708",
                            Name = "São Bernardo do Campo",
                            StateId = 25
                        },
                        new
                        {
                            Id = 63,
                            IbgeCode = "4106902",
                            Name = "Curitiba",
                            StateId = 16
                        },
                        new
                        {
                            Id = 64,
                            IbgeCode = "4113700",
                            Name = "Londrina",
                            StateId = 16
                        },
                        new
                        {
                            Id = 65,
                            IbgeCode = "4115200",
                            Name = "Maringá",
                            StateId = 16
                        },
                        new
                        {
                            Id = 66,
                            IbgeCode = "4205407",
                            Name = "Florianópolis",
                            StateId = 24
                        },
                        new
                        {
                            Id = 67,
                            IbgeCode = "4209102",
                            Name = "Joinville",
                            StateId = 24
                        },
                        new
                        {
                            Id = 68,
                            IbgeCode = "4202404",
                            Name = "Blumenau",
                            StateId = 24
                        },
                        new
                        {
                            Id = 69,
                            IbgeCode = "4314902",
                            Name = "Porto Alegre",
                            StateId = 21
                        },
                        new
                        {
                            Id = 70,
                            IbgeCode = "4305108",
                            Name = "Caxias do Sul",
                            StateId = 21
                        },
                        new
                        {
                            Id = 71,
                            IbgeCode = "4314407",
                            Name = "Pelotas",
                            StateId = 21
                        },
                        new
                        {
                            Id = 72,
                            IbgeCode = "5002704",
                            Name = "Campo Grande",
                            StateId = 12
                        },
                        new
                        {
                            Id = 73,
                            IbgeCode = "5003702",
                            Name = "Dourados",
                            StateId = 12
                        },
                        new
                        {
                            Id = 74,
                            IbgeCode = "5103403",
                            Name = "Cuiabá",
                            StateId = 11
                        },
                        new
                        {
                            Id = 75,
                            IbgeCode = "5108402",
                            Name = "Várzea Grande",
                            StateId = 11
                        },
                        new
                        {
                            Id = 76,
                            IbgeCode = "5107602",
                            Name = "Rondonópolis",
                            StateId = 11
                        },
                        new
                        {
                            Id = 77,
                            IbgeCode = "5208707",
                            Name = "Goiânia",
                            StateId = 9
                        },
                        new
                        {
                            Id = 78,
                            IbgeCode = "5201405",
                            Name = "Aparecida de Goiânia",
                            StateId = 9
                        },
                        new
                        {
                            Id = 79,
                            IbgeCode = "5201108",
                            Name = "Anápolis",
                            StateId = 9
                        },
                        new
                        {
                            Id = 80,
                            IbgeCode = "5300108",
                            Name = "Brasília",
                            StateId = 7
                        });
                });

            modelBuilder.Entity("LandmarkApi.Domain.Entities.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("IbgeCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Acronym")
                        .IsUnique();

                    b.HasIndex("IbgeCode")
                        .IsUnique();

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Acronym = "AC",
                            IbgeCode = "12",
                            Name = "Acre"
                        },
                        new
                        {
                            Id = 2,
                            Acronym = "AL",
                            IbgeCode = "27",
                            Name = "Alagoas"
                        },
                        new
                        {
                            Id = 3,
                            Acronym = "AP",
                            IbgeCode = "16",
                            Name = "Amapá"
                        },
                        new
                        {
                            Id = 4,
                            Acronym = "AM",
                            IbgeCode = "13",
                            Name = "Amazonas"
                        },
                        new
                        {
                            Id = 5,
                            Acronym = "BA",
                            IbgeCode = "29",
                            Name = "Bahia"
                        },
                        new
                        {
                            Id = 6,
                            Acronym = "CE",
                            IbgeCode = "23",
                            Name = "Ceará"
                        },
                        new
                        {
                            Id = 7,
                            Acronym = "DF",
                            IbgeCode = "53",
                            Name = "Distrito Federal"
                        },
                        new
                        {
                            Id = 8,
                            Acronym = "ES",
                            IbgeCode = "32",
                            Name = "Espírito Santo"
                        },
                        new
                        {
                            Id = 9,
                            Acronym = "GO",
                            IbgeCode = "52",
                            Name = "Goiás"
                        },
                        new
                        {
                            Id = 10,
                            Acronym = "MA",
                            IbgeCode = "21",
                            Name = "Maranhão"
                        },
                        new
                        {
                            Id = 11,
                            Acronym = "MT",
                            IbgeCode = "51",
                            Name = "Mato Grosso"
                        },
                        new
                        {
                            Id = 12,
                            Acronym = "MS",
                            IbgeCode = "50",
                            Name = "Mato Grosso do Sul"
                        },
                        new
                        {
                            Id = 13,
                            Acronym = "MG",
                            IbgeCode = "31",
                            Name = "Minas Gerais"
                        },
                        new
                        {
                            Id = 14,
                            Acronym = "PA",
                            IbgeCode = "15",
                            Name = "Pará"
                        },
                        new
                        {
                            Id = 15,
                            Acronym = "PB",
                            IbgeCode = "25",
                            Name = "Paraíba"
                        },
                        new
                        {
                            Id = 16,
                            Acronym = "PR",
                            IbgeCode = "41",
                            Name = "Paraná"
                        },
                        new
                        {
                            Id = 17,
                            Acronym = "PE",
                            IbgeCode = "26",
                            Name = "Pernambuco"
                        },
                        new
                        {
                            Id = 18,
                            Acronym = "PI",
                            IbgeCode = "22",
                            Name = "Piauí"
                        },
                        new
                        {
                            Id = 19,
                            Acronym = "RJ",
                            IbgeCode = "33",
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 20,
                            Acronym = "RN",
                            IbgeCode = "24",
                            Name = "Rio Grande do Norte"
                        },
                        new
                        {
                            Id = 21,
                            Acronym = "RS",
                            IbgeCode = "43",
                            Name = "Rio Grande do Sul"
                        },
                        new
                        {
                            Id = 22,
                            Acronym = "RO",
                            IbgeCode = "11",
                            Name = "Rondônia"
                        },
                        new
                        {
                            Id = 23,
                            Acronym = "RR",
                            IbgeCode = "14",
                            Name = "Roraima"
                        },
                        new
                        {
                            Id = 24,
                            Acronym = "SC",
                            IbgeCode = "42",
                            Name = "Santa Catarina"
                        },
                        new
                        {
                            Id = 25,
                            Acronym = "SP",
                            IbgeCode = "35",
                            Name = "São Paulo"
                        },
                        new
                        {
                            Id = 26,
                            Acronym = "SE",
                            IbgeCode = "28",
                            Name = "Sergipe"
                        },
                        new
                        {
                            Id = 27,
                            Acronym = "TO",
                            IbgeCode = "17",
                            Name = "Tocantins"
                        });
                });

            modelBuilder.Entity("LandmarkApi.Domain.Entities.TouristPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("TouristPoints", (string)null);
                });

            modelBuilder.Entity("LandmarkApi.Domain.Entities.City", b =>
                {
                    b.HasOne("LandmarkApi.Domain.Entities.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("LandmarkApi.Domain.Entities.TouristPoint", b =>
                {
                    b.HasOne("LandmarkApi.Domain.Entities.City", "City")
                        .WithMany("TouristPoints")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("LandmarkApi.Domain.Entities.City", b =>
                {
                    b.Navigation("TouristPoints");
                });

            modelBuilder.Entity("LandmarkApi.Domain.Entities.State", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
